### PR TITLE
Refine test coverage

### PR DESCRIPTION
**Pull request by pellared**
Addresses https://github.com/golang-templates/seed/issues/41

- Refine `test` make target to get better coverage result and create HTML coverage report
- Upload the test coverage HTML report as build artifact. See: https://github.com/golang-templates/seed/suites/870302777/artifacts/10110210

### CODE REVIEW

**Comment by masch** [comment]
It look fine to me.

You have a great readme documentation,  so What do you think about to add an entry on it about the feature of uploading the test coverage result  as a github artifact?

**Comment by pellared** [comment]
Sure, I will try to enhance README.md. I am not good at writing, but I will do my best.

I tested the stuff on more project and it looks like `-coverpkg=./...` causes often trouble. The tests where panicing from unknown reason. I see two options:

1. Use https://github.com/ory/go-acc. [Read more.](https://www.ory.sh/golang-go-code-coverage-accurate/)
1. Get rid of `-coverpkg=./...` and accept the fact that the toolchain recording code coverage for the package that is currently tested. Add FAQ section about it and how to get better results using `go-acc`.

What do you think?

**Comment by masch** [comment]
I think that the approach that you took is great! I think that you wrote a good explanation on why you decided it and also you gave a good alternative if someone want to use `-coverpkg` option.

If you let me one more comment please, I know it's none of my business, but I'm :nerd_face: on git commits history too.
In orde order to improve git history, I think it'll be better if you squash and rebase your git commits.
I know is a personal opinion, but here is a good article on why is that: https://blog.carbonfive.com/always-squash-and-rebase-your-git-commits/ 

As you might know, English is not my first language and I'm sorry if I'm not good enough to just leave a suggestion on this personal comment.

**Comment by pellared** [comment]
Thanks a lot for review and feedback.

Usually I squash the commits and merge and sometimes just rebase and merge. Depends on the PR :wink:
You may be interested in https://www.conventionalcommits.org/en/v1.0.0/ as well as https://chris.beams.io/posts/git-commit/ .

**Pull request merged**
